### ISSUE TITLE
As a user, I would like to have a way to see a summary of current filters applied to the visual

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#15]
This is regarding the "subtitle" to transparently indicate what filters are applied.

**Comment by j9recurses** [comment]
This is not closed...
we need to explicitly pass whats being filtered to the chart subtitle component. 

<img width="1280" alt="screen shot 2016-12-05 at 11 51 41 am" src="https://cloud.githubusercontent.com/assets/6549842/20899996/76a4f326-bae1-11e6-8731-38c3e25639f0.png">

**Comment by jasonlally** [comment]
Duplicate of #191

**Comment by j9recurses** [comment]
This is done- Except for Boolean because the actual filter is broken.
Screenshots of finished product are below. 

<img width="1280" alt="screen shot 2017-01-25 at 12 56 20 pm" src="https://cloud.githubusercontent.com/assets/6549842/22311917/897afa1c-e30a-11e6-9c39-3d66a471bf9e.png">
<img width="1280" alt="screen shot 2017-01-25 at 12 56 03 pm" src="https://cloud.githubusercontent.com/assets/6549842/22311918/897d498e-e30a-11e6-8097-65bd2d928a05.png">
<img width="1280" alt="screen shot 2017-01-25 at 12 55 26 pm" src="https://cloud.githubusercontent.com/assets/6549842/22311919/897d64be-e30a-11e6-930e-3eab82762367.png">

**Comment by jasonlally** [comment]
Closed by #232
